#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Oct 18 13:33:39 EDT 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 832a455316324ba59b0b5d871d2ca7a3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ARP_RESPONSE_TB_behav xil_defaultlib.ARP_RESPONSE_TB -log elaborate.log"
xelab -wto 832a455316324ba59b0b5d871d2ca7a3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ARP_RESPONSE_TB_behav xil_defaultlib.ARP_RESPONSE_TB -log elaborate.log

