#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 17 22:55:23 EDT 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim ARP_RESPONSE_TB_behav -key {Behavioral:sim_1:Functional:ARP_RESPONSE_TB} -tclbatch ARP_RESPONSE_TB.tcl -view /home/joe/xr_trading/ARP_RESPONSE_TB_behav.wcfg -log simulate.log"
xsim ARP_RESPONSE_TB_behav -key {Behavioral:sim_1:Functional:ARP_RESPONSE_TB} -tclbatch ARP_RESPONSE_TB.tcl -view /home/joe/xr_trading/ARP_RESPONSE_TB_behav.wcfg -log simulate.log

